// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: Owner.proto

package protos

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Pet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type      string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	BirthDate int64  `protobuf:"varint,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
}

func (x *Pet) Reset() {
	*x = Pet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Owner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_Owner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_Owner_proto_rawDescGZIP(), []int{0}
}

func (x *Pet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Pet) GetBirthDate() int64 {
	if x != nil {
		return x.BirthDate
	}
	return 0
}

type OwnerIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Address   string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	City      string `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	State     string `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	ZipCode   string `protobuf:"bytes,7,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Email     string `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Telephone string `protobuf:"bytes,9,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Pets      *Pet   `protobuf:"bytes,10,opt,name=pets,proto3" json:"pets,omitempty"`
}

func (x *OwnerIndexRequest) Reset() {
	*x = OwnerIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Owner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnerIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerIndexRequest) ProtoMessage() {}

func (x *OwnerIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Owner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerIndexRequest.ProtoReflect.Descriptor instead.
func (*OwnerIndexRequest) Descriptor() ([]byte, []int) {
	return file_Owner_proto_rawDescGZIP(), []int{1}
}

func (x *OwnerIndexRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OwnerIndexRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *OwnerIndexRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *OwnerIndexRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OwnerIndexRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *OwnerIndexRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OwnerIndexRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *OwnerIndexRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OwnerIndexRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *OwnerIndexRequest) GetPets() *Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

type OwnerIndexResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
}

func (x *OwnerIndexResponse) Reset() {
	*x = OwnerIndexResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Owner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnerIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerIndexResponse) ProtoMessage() {}

func (x *OwnerIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Owner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerIndexResponse.ProtoReflect.Descriptor instead.
func (*OwnerIndexResponse) Descriptor() ([]byte, []int) {
	return file_Owner_proto_rawDescGZIP(), []int{2}
}

func (x *OwnerIndexResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OwnerIndexResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_Owner_proto protoreflect.FileDescriptor

var file_Owner_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72,
	0x61, 0x74, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x5c, 0x0a, 0x03, 0x50, 0x65,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62,
	0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x22, 0x98, 0x02, 0x0a, 0x11, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x7a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x24, 0x0a,
	0x04, 0x70, 0x65, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x61,
	0x74, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x65, 0x74, 0x52, 0x04, 0x70,
	0x65, 0x74, 0x73, 0x22, 0x50, 0x0a, 0x12, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x64, 0x0a, 0x11, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x72, 0x61, 0x74, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x61, 0x74, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x0a, 0x0d, 0x63,
	0x6f, 0x6d, 0x2e, 0x70, 0x65, 0x74, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x42, 0x11, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_Owner_proto_rawDescOnce sync.Once
	file_Owner_proto_rawDescData = file_Owner_proto_rawDesc
)

func file_Owner_proto_rawDescGZIP() []byte {
	file_Owner_proto_rawDescOnce.Do(func() {
		file_Owner_proto_rawDescData = protoimpl.X.CompressGZIP(file_Owner_proto_rawDescData)
	})
	return file_Owner_proto_rawDescData
}

var file_Owner_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Owner_proto_goTypes = []interface{}{
	(*Pet)(nil),                // 0: rateservice.Pet
	(*OwnerIndexRequest)(nil),  // 1: rateservice.OwnerIndexRequest
	(*OwnerIndexResponse)(nil), // 2: rateservice.OwnerIndexResponse
}
var file_Owner_proto_depIdxs = []int32{
	0, // 0: rateservice.OwnerIndexRequest.pets:type_name -> rateservice.Pet
	1, // 1: rateservice.OwnerIndexService.IndexOwner:input_type -> rateservice.OwnerIndexRequest
	2, // 2: rateservice.OwnerIndexService.IndexOwner:output_type -> rateservice.OwnerIndexResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Owner_proto_init() }
func file_Owner_proto_init() {
	if File_Owner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Owner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Owner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnerIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Owner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnerIndexResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Owner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Owner_proto_goTypes,
		DependencyIndexes: file_Owner_proto_depIdxs,
		MessageInfos:      file_Owner_proto_msgTypes,
	}.Build()
	File_Owner_proto = out.File
	file_Owner_proto_rawDesc = nil
	file_Owner_proto_goTypes = nil
	file_Owner_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OwnerIndexServiceClient is the client API for OwnerIndexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OwnerIndexServiceClient interface {
	IndexOwner(ctx context.Context, in *OwnerIndexRequest, opts ...grpc.CallOption) (*OwnerIndexResponse, error)
}

type ownerIndexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOwnerIndexServiceClient(cc grpc.ClientConnInterface) OwnerIndexServiceClient {
	return &ownerIndexServiceClient{cc}
}

func (c *ownerIndexServiceClient) IndexOwner(ctx context.Context, in *OwnerIndexRequest, opts ...grpc.CallOption) (*OwnerIndexResponse, error) {
	out := new(OwnerIndexResponse)
	err := c.cc.Invoke(ctx, "/rateservice.OwnerIndexService/IndexOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OwnerIndexServiceServer is the server API for OwnerIndexService service.
type OwnerIndexServiceServer interface {
	IndexOwner(context.Context, *OwnerIndexRequest) (*OwnerIndexResponse, error)
}

// UnimplementedOwnerIndexServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOwnerIndexServiceServer struct {
}

func (*UnimplementedOwnerIndexServiceServer) IndexOwner(context.Context, *OwnerIndexRequest) (*OwnerIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexOwner not implemented")
}

func RegisterOwnerIndexServiceServer(s *grpc.Server, srv OwnerIndexServiceServer) {
	s.RegisterService(&_OwnerIndexService_serviceDesc, srv)
}

func _OwnerIndexService_IndexOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OwnerIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwnerIndexServiceServer).IndexOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rateservice.OwnerIndexService/IndexOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwnerIndexServiceServer).IndexOwner(ctx, req.(*OwnerIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OwnerIndexService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rateservice.OwnerIndexService",
	HandlerType: (*OwnerIndexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexOwner",
			Handler:    _OwnerIndexService_IndexOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Owner.proto",
}
