version: "3.8"

services:
# cassandra will not be exposed to the loadbalancer and reverse proxy
  cassandra:
    image: cassandra:3
    container_name: pc_cassandra
    networks:
      - petclinic_net
    volumes:
      - petclinic_api_data:/var/lib/cassandra

# traefik is the external load balancer and reverse proxy where all apps are going through the 
  traefik:
    image: "traefik:2.2.8"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    command:
       - "--api.insecure=true"
       - "--providers.docker=true"
       - "--providers.docker.network=traefik-internal-proxy"
       - "--providers.docker.exposedbydefault=false"
       - "--entrypoints.web.address=:80"
       - "--entrypoints.websecure.address=:443"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-internal-proxy

  petclini-api:
    image: rnkoaa/petclinic-api:latest
    container_name: petclinic-api
    environment:
      - "CONTAINER_MEM_MB=256"
      - "SPRING_DATA_CASSANDRA_CONSISTENCYLEVEL=local_one"
      - "SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra"
    restart: always
    depends_on:
      - cassandra
    networks:
      - petclinic_net
      - traefik-internal-proxy
    ports:
      - 9092:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=(Host(`localhost`) && PathPrefix(`/api`))"
      - "traefik.http.routers.api.middlewares=api-stripprefix"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
  
# http://localhost/search?q=dav&type=owner&result_fields=first_name,last_name,email,phone&fields=email,first_name,last_name,phone
  search:
    image: rnkoaa/petclinic-search:latest
    ports:
    - 9090:8080
    environment:
    - 9090:8080
    - DATA_DIR=/var/lib/petclinic
    volumes:
      - search-data:/var/lib/petclinic
    networks:
    - traefik-internal-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.search.rule=(Host(`localhost`) && PathPrefix(`/search`))"
      - "traefik.http.routers.search.middlewares=search-stripprefix"
      - "traefik.http.middlewares.search-stripprefix.stripprefix.prefixes=/search"


volumes:
  petclinic_api_data:
    external: true
  search-data:
    external: true

networks:
  petclinic_net:
    external: true
  traefik-internal-proxy:
    external: true
